name: Java CI

on:
  push:
    branches: [ "sit1" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Sonar Analysis
      working-directory: /home/ubuntu/actions-runner/_work/B2C/B2C/ecommerce-multivendor-backend-master
      env:
        SONAR_HOST_URL: http://15.207.180.250:9000/
        SONAR_LOGIN: squ_6a4ae691d399eca00a825b57480cdbc88bfc5d0f 
        SONAR_PROJECT_NAME: b2b1
        SONAR_PROJECT_KEY: b2b1
      run: |
        mvn sonar:sonar \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN \
          -Dsonar.projectName=$SONAR_PROJECT_NAME \
          -Dsonar.java.binaries=. \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY
          
    - name: OWASP Dependency Check
      run: |
        dependency-check --scan /home/ubuntu/actions-runner/_work/B2C/B2C/ecommerce-multivendor-backend-master/target --format XML --project B2B --out /tmp/dependency-check-report

    - name: Archive Dependency Check reports
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: /tmp/dependency-check-report/dependency-check-report.xml

    - name: Build with Maven
      working-directory: ./ecommerce-multivendor-backend-master
      run: mvn clean install
      
    - name: List Target Directory
      run: ls ./ecommerce-multivendor-backend-master/target
      
    - name: Upload Artifact to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ./ecommerce-multivendor-backend-master/target/*.jar
